version: '3'
services:
    redis:
        image: redis:6.0.8-alpine
    db:
        image: postgres:13-alpine
        environment:
            - POSTGRES_PASSWORD=process_app
            - POSTGRES_USER=process_app
            - POSTGRES_DB=process_app_dev
    breaker:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - "./app.py:/application/app.py"
            - "breaker_storage:/tmp/flask_uploads"
        depends_on:
            - redis
            - db
    worker:
        build: .
        volumes:
            - "worker_state:/var/run/celery"
        command: celery -A app.celery worker -l INFO
        depends_on:
            - breaker
        volumes:
            - "./worker.pem:/etc/ssl/certs/worker.pem"
            - "./worker.key:/etc/ssl/private/worker.key"
volumes:
    worker_state:
    breaker_storage: